name = "HomogeneousCoordinate"
uuid = "f802b418-ed3b-4880-b0e6-ca3803886e5b"
authors = ["Yukun Guo <gyk.net@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
