[package]
name = "sliding_puzzle"
version = "0.1.0"
authors = ["Yukun Guo <gyk.net@gmail.com>"]
edition = "2018"

[dependencies]
keyed_priority_queue = "0.2"
lazy_static = "1.4"

[dev-dependencies]
rand = "0.7"
