[package]
name = "shamir-secret-sharing"
version = "0.1.0"
authors = ["Yukun Guo <gyk.net@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.2"
num = "0.2"
num-traits = "0.2"
rand = "0.6"

[dev-dependencies]
proptest = "0.9"
