name = "ConjugateGradientMethod"
uuid = "0cf3b561-e86e-4731-a990-fdee25468c8c"
authors = ["Yukun Guo <gyk.net@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
